### PR TITLE
bug: set auto accept not working correctly

### LINKED ISSUE #60: SetAutoAccept not working correctly
Changing autoaccept at runtime seems to have issues. When changing it during runtime, the mDNS record does not get updated. This is likely because the previous record isn't getting removed and the new record getting published.

This needs investigation.

### PR DESCRIPTION
**Pull request by randomdudebunchofnumbers**
Adds missing mdns unannounce on auto accept state changed

Fixes #60

### CODE REVIEW

File: mdns/mdns_test.go [hunk 1]
```diff
@@ -823,3 +824,78 @@ func (s *MdnsSuite) Test_Shutdown_DefensiveProgramming() {
 	// Verify provider is cleaned up (defensive shutdown succeeded)
 	assert.Nil(s.T(), manager.mdnsProvider)
 }
+
+func (s *MdnsSuite) Test_AutoAccepServiceUnannouncedYet() {
```
Comment (DerAndereAndi) [inline mdns/mdns_test.go]: Minor Typo `Test_AutoAccepServiceUnannouncedYet` missing the `t` of `Accept`. So it should be `Test_AutoAcceptServiceUnannouncedYet`

File: mdns/mdns.go [hunk 2]
```diff
@@ -381,10 +381,25 @@ func (m *MdnsManager) SetAutoAccept(accept bool) {
...
+	err := m.AnnounceMdnsEntry()
+
+	if err == nil {
+		return
 	}
+
+	logging.Log().Debug("mdns: changing mdns entry failed", err)
+
+	m.mux.Lock()
+	defer m.mux.Unlock()
```
Comment (DerAndereAndi) [inline mdns/mdns.go]: The Lock here is not needed.

**Review by DerAndereAndi — CHANGES_REQUESTED** [review]
Thanks for the PR. Looks good only with 2 minor remarks.

File: mdns/mdns_test.go (hunk 1 above)
Comment (randomdudebunchofnumbers) [reply mdns/mdns_test.go]: fixed in latest commit

File: mdns/mdns.go (hunk 2 above)
Comment (randomdudebunchofnumbers) [reply mdns/mdns.go]: Fixed in latest commit. This seems to have been a copy-paste error - check lines 338-339 of the current dev. I fixed both places.

**Review by DerAndereAndi — APPROVED** [review]

**Comment by DerAndereAndi** [comment]
Thanks @randomdudebunchofnumbers looks good to me. Simon will also take a look.
